version: "3.8"

services:
  postgres:
    image: postgres:18.3
    container_name: menu-qr-admin
    restart: unless-stopped
    environment:
      POSTGRES_USER: qr_admin
      POSTGRES_PASSWORD: qr_password
      POSTGRES_DB: menu_qr_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
